# fly.toml app configuration file generated for my-crypto-app on 2023-09-28T10:20:12+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-crypto-app"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
